name: Chef Cookbook Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  chef_poc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install ChefDK
        run: |
          curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P chefdk -v 4.13.3

      - name: Run Chef Client in local mode PoC
        env:
          CHEF_LICENSE: accept
        run: |
          sudo -E chef-client -z -j roles/webserver.json -o 'recipe[site_webserver::default]' --why-run
