name: Chef Cookbook Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install ChefDK
        run: |
          curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P chefdk -v 4.13.3

      - name: Install Test Kitchen and dependencies
        run: |
          chef gem install kitchen-dokken kitchen-inspec

      - name: Run Foodcritic (lint Chef cookbook)
        run: |
          foodcritic .

      - name: Run Test Kitchen converge + verify
        run: |
          kitchen test
